server:
  port: 8090
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: 'prod'

  datasource:
    url: jdbc:mariadb://HOST:3306/DB_NAME?useUnicode=true&characterEncoding=UTF-8&autoreconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username:
    password:

app:
  cors:
    enable: true
    allowed-origins:
      - https://*.giprecia.net

  soffit:
    jwt-signature-key: ''

  storage:
    location: ''

  front:
    websocket:
      url: ''

    extended-uportal-header:
      context-api-url: ''
      sign-out-url: ''
      default-org-logo-path: ''
      default-avatar-path: ''
      default-org-icon-path: ''
      favorite-api-url: ''
      layout-api-url: ''
      organization-api-url: ''
      portlet-api-url: ''
      user-info-api-url: ''
      user-info-portlet-url: ''
      session-api-url: ''
      template-api-path: ''
      switch-org-portlet-url: ''
      favorites-portlet-card-size: ''
      grid-portlet-card-size: ''
      hide-action-mode: ''
      show-favorites-in-slider: ''
      return-home-title: ''
      return-home-target: ''
      icon-type: ''

    extended-uportal-footer:
      template-api-path: ''
