spring:
  config:
    activate:
      on-profile: 'default-config'

---

server:
  port: 8090
  servlet:
    context-path: /spring-api

logging:
  config: 'classpath:logback.xml'

spring:
  application:
    name: Collabosoft

  profiles:
    active: @spring.profiles.active@
    group:
      dev: dev
      test: test
      prod: prod
      ci: test

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

app:
  cors:
    enable: true
    allow-credentials: true
    allowed-origins:
      - http://localhost:5173
      - https://*.giprecia.net
    exposed-headers:
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-headers:
      - content-type
      - authorization
      - x-com-persist
      - X-Auth-Token
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-methods:
      - GET
      - PUT
      - POST
      - DELETE

  soffit:
    jwt-signature-key: ''

  storage:
    location: ''

  front:
    appName: ''

    user-info-api-url: ''

    nextcloud-uri: ''

    collaboration:
      websocket-api-url: ''

    extended-uportal-header:
      component-path: ''
      context-api-url: ''
      sign-out-url: ''
      default-org-logo-path: ''
      default-avatar-path: ''
      default-org-icon-path: ''
      favorite-api-url: ''
      layout-api-url: ''
      organization-api-url: ''
      portlet-api-url: ''
      user-info-api-url: ''
      user-info-portlet-url: ''
      session-api-url: ''
      template-api-path: ''
      switch-org-portlet-url: ''
      favorites-portlet-card-size: ''
      grid-portlet-card-size: ''
      hide-action-mode: ''
      show-favorites-in-slider: ''
      return-home-title: ''
      return-home-target: ''
      icon-type: ''

    extended-uportal-footer:
      component-path: ''
      template-api-path: ''
